# Makefile
#  auther  Ahmed Samieh
#  email   ahmed.samieh@gmail.com

all:
	g++ hinv.cpp -I../ ../hypergraph_inverse.cpp ../hypergraph_file.cpp -o hinv
	g++ hpairs.cpp -I../ ../hypergraph_file.cpp -o hpairs

clean:
	rm -rf hinv hpairs

